# Generated by Django 3.1 on 2021-01-27 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_editing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='status',
            field=models.CharField(choices=[('II', 'Initial Idea'), ('AE', 'Awaiting Editor'), ('AR', 'Awaiting Review'), ('ID', 'Idea in Development'), ('IA', 'Idea in Development (Answer Assigned)'), ('AA', 'Awaiting Answer'), ('W', 'Writing (Answer Assigned)'), ('WF', 'Writing (Answer Flexible)'), ('AT', 'Awaiting Approval for Testsolving'), ('T', 'Testsolving'), ('R', 'Revising'), ('NS', 'Needs Solution'), ('NP', 'Needs Post Production'), ('NF', 'Needs Factcheck'), ('NR', 'Needs Final Revisions'), ('NC', 'Needs Copy Edits'), ('NH', 'Needs Hints'), ('D', 'Done'), ('DF', 'Deferred'), ('X', 'Dead')], default='II', max_length=2),
        ),
        migrations.AlterField(
            model_name='statussubscription',
            name='status',
            field=models.CharField(choices=[('II', 'Initial Idea'), ('AE', 'Awaiting Editor'), ('AR', 'Awaiting Review'), ('ID', 'Idea in Development'), ('IA', 'Idea in Development (Answer Assigned)'), ('AA', 'Awaiting Answer'), ('W', 'Writing (Answer Assigned)'), ('WF', 'Writing (Answer Flexible)'), ('AT', 'Awaiting Approval for Testsolving'), ('T', 'Testsolving'), ('R', 'Revising'), ('NS', 'Needs Solution'), ('NP', 'Needs Post Production'), ('NF', 'Needs Factcheck'), ('NR', 'Needs Final Revisions'), ('NC', 'Needs Copy Edits'), ('NH', 'Needs Hints'), ('D', 'Done'), ('DF', 'Deferred'), ('X', 'Dead')], max_length=2),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.FloatField(help_text='Order in the puzzle - use 0 for a hint at the very beginning of the puzzle, or 100 for a hint on extraction, and then do your best to extrapolate in between. Decimals are okay. For multiple subpuzzles, assign a whole number to each subpuzzle and use decimals off of that whole number for multiple hints in the subpuzzle.')),
                ('keywords', models.CharField(blank=True, help_text="Comma-separated keywords to look for in hunters' hint requests before displaying this hint suggestion", max_length=100)),
                ('content', models.CharField(help_text='Canned hint to give a team (can be edited by us before giving it)', max_length=1000)),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hints', to='puzzle_editing.puzzle')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
