# Generated by Django 3.1 on 2021-02-08 04:27
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


REV_STATUS_MAP = {
    "Initial Idea": "II",
    "Awaiting Editor": "AE",
    "Awaiting Review": "AR",
    "Idea in Development": "ID",
    "Idea in Development (Answer Assigned)": "IA",
    "Awaiting Answer": "AA",
    "Writing (Answer Assigned)": "W",
    "Writing (Answer Flexible)": "WF",
    "Awaiting Approval for Testsolving": "AT",
    "Testsolving": "T",
    "Revising": "R",  # old
    "Revising (Needs Testsolving)": "R",  # new
    "Revising (Done with Testsolving)": "RP",
    "Awaiting Approval (Done with Testsolving)": "AO",
    "Needs Solution": "NS",
    "Awaiting Solution Approval": "AS",
    "Needs Post Production": "NP",
    "Awaiting Postprod Approval": "AP",
    "Needs Factcheck": "NF",
    "Needs Final Revisions": "NR",
    "Needs Copy Edits": "NC",
    "Needs Hints": "NH",
    "Awaiting Hints Approval": "AH",
    "Done": "D",
    "Deferred": "DF",
    "Dead": "X",
}


def retrofit_status_changes(apps, schema_editor):
    PuzzleComment = apps.get_model("puzzle_editing", "PuzzleComment")
    for comment in PuzzleComment.objects.all():
        content = comment.content
        if content == "Created puzzle":
            comment.content = ""
            comment.status_change = "II"
            comment.save()
        elif (
            content.startswith("Status changed to ") and content[18:] in REV_STATUS_MAP
        ):
            comment.content = ""
            comment.status_change = REV_STATUS_MAP[content[18:]]
            comment.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("puzzle_editing", "0002_auto_20210127_0752"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="puzzle",
            old_name="needed_discussion_editors",
            new_name="needed_editors",
        ),
        migrations.RenameField(
            model_name="puzzle", old_name="discussion_editors", new_name="editors",
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="editors",
            field=models.ManyToManyField(
                blank=True, related_name="editing_puzzles", to=settings.AUTH_USER_MODEL
            ),
        ),
        # migrations.RemoveField(
        #     model_name='puzzle',
        #     name='discussion_editors',
        # ),
        # migrations.AddField(
        #     model_name='puzzle',
        #     name='editors',
        #     field=models.ManyToManyField(blank=True, related_name='editing_puzzles', to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AddField(
            model_name="puzzlecomment",
            name="status_change",
            field=models.CharField(
                blank=True,
                choices=[
                    ("II", "Initial Idea"),
                    ("AE", "Awaiting Editor"),
                    ("AR", "Awaiting Review"),
                    ("ID", "Idea in Development"),
                    ("IA", "Idea in Development (Answer Assigned)"),
                    ("AA", "Awaiting Answer"),
                    ("W", "Writing (Answer Assigned)"),
                    ("WF", "Writing (Answer Flexible)"),
                    ("AT", "Awaiting Approval for Testsolving"),
                    ("T", "Testsolving"),
                    ("R", "Revising (Needs Testsolving)"),
                    ("RP", "Revising (Done with Testsolving)"),
                    ("AO", "Awaiting Approval (Done with Testsolving)"),
                    ("NS", "Needs Solution"),
                    ("AS", "Awaiting Solution Approval"),
                    ("NP", "Needs Post Production"),
                    ("AP", "Awaiting Postprod Approval"),
                    ("NF", "Needs Factcheck"),
                    ("NR", "Needs Final Revisions"),
                    ("NC", "Needs Copy Edits"),
                    ("NH", "Needs Hints"),
                    ("AH", "Awaiting Hints Approval"),
                    ("D", "Done"),
                    ("DF", "Deferred"),
                    ("X", "Dead"),
                ],
                help_text="Any status change caused by this comment. Only used for recording history and computing statistics; not a source of truth (i.e. the puzzle will still store its current status, and this field's value on any comment doesn't directly imply anything about that in any technically enforced way).",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="puzzle",
            name="status",
            field=models.CharField(
                choices=[
                    ("II", "Initial Idea"),
                    ("AE", "Awaiting Editor"),
                    ("AR", "Awaiting Review"),
                    ("ID", "Idea in Development"),
                    ("IA", "Idea in Development (Answer Assigned)"),
                    ("AA", "Awaiting Answer"),
                    ("W", "Writing (Answer Assigned)"),
                    ("WF", "Writing (Answer Flexible)"),
                    ("AT", "Awaiting Approval for Testsolving"),
                    ("T", "Testsolving"),
                    ("R", "Revising (Needs Testsolving)"),
                    ("RP", "Revising (Done with Testsolving)"),
                    ("AO", "Awaiting Approval (Done with Testsolving)"),
                    ("NS", "Needs Solution"),
                    ("AS", "Awaiting Solution Approval"),
                    ("NP", "Needs Post Production"),
                    ("AP", "Awaiting Postprod Approval"),
                    ("NF", "Needs Factcheck"),
                    ("NR", "Needs Final Revisions"),
                    ("NC", "Needs Copy Edits"),
                    ("NH", "Needs Hints"),
                    ("AH", "Awaiting Hints Approval"),
                    ("D", "Done"),
                    ("DF", "Deferred"),
                    ("X", "Dead"),
                ],
                default="II",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="puzzlecomment",
            name="content",
            field=models.TextField(
                blank=True,
                help_text="The content of the comment. Should probably only be blank if the status_change is set.",
            ),
        ),
        migrations.AlterField(
            model_name="statussubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("II", "Initial Idea"),
                    ("AE", "Awaiting Editor"),
                    ("AR", "Awaiting Review"),
                    ("ID", "Idea in Development"),
                    ("IA", "Idea in Development (Answer Assigned)"),
                    ("AA", "Awaiting Answer"),
                    ("W", "Writing (Answer Assigned)"),
                    ("WF", "Writing (Answer Flexible)"),
                    ("AT", "Awaiting Approval for Testsolving"),
                    ("T", "Testsolving"),
                    ("R", "Revising (Needs Testsolving)"),
                    ("RP", "Revising (Done with Testsolving)"),
                    ("AO", "Awaiting Approval (Done with Testsolving)"),
                    ("NS", "Needs Solution"),
                    ("AS", "Awaiting Solution Approval"),
                    ("NP", "Needs Post Production"),
                    ("AP", "Awaiting Postprod Approval"),
                    ("NF", "Needs Factcheck"),
                    ("NR", "Needs Final Revisions"),
                    ("NC", "Needs Copy Edits"),
                    ("NH", "Needs Hints"),
                    ("AH", "Awaiting Hints Approval"),
                    ("D", "Done"),
                    ("DF", "Deferred"),
                    ("X", "Dead"),
                ],
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.CharField(max_length=8)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="puzzle_editing.puzzlecomment",
                    ),
                ),
                (
                    "reactor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("emoji", "comment", "reactor")},},
        ),
        migrations.RunPython(retrofit_status_changes),
    ]
