# Generated by Django 3.1.8 on 2021-06-19 04:14
from django.db import migrations
from django.db import models

import puzzle_editing.models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzle_editing", "0003_auto_20210208_0427"),
    ]

    operations = [
        migrations.AddField(
            model_name="puzzle",
            name="uploaded_content",
            field=models.FileField(
                blank=True,
                help_text="An uploaded file of the puzzle itself. It may be a text file, PDF, etc. or it may be a zip file containing an index.html page as well as additional assets.",
                null=True,
                upload_to=puzzle_editing.models.Puzzle.uploaded_content_path,
            ),
        ),
        migrations.AddField(
            model_name="puzzle",
            name="uploaded_solution",
            field=models.FileField(
                blank=True,
                help_text="An uploaded file of the puzzle solution. It may be a text file, PDF, etc. or it may be a zip file containing an index.html page as well as additional assets.",
                null=True,
                upload_to=puzzle_editing.models.Puzzle.uploaded_solution_path,
            ),
        ),
    ]
